name: check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - name: Check formatting
        run: |
          cargo fmt --check
      - name: Check lint
        run: |-
          cargo clippy --no-deps -- --deny warnings